version: '3'

services:
  nginx:
    container_name: zkusebna-kobylisy-nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    container_name: zkusebna-kobylisy
    build: .
    expose:
      - 3000
    volumes:
      - ../../:/usr/src/app/
      - ./run.sh:/run.sh
      - app-node-modules:/usr/src/app/node_modules/
      
  mongo:
    container_name: zkusebna-kobylisy-mongo
    image: mongo
    expose:
      - 27017

volumes:
  app-node-modules:
