# courtesy of https://github.com/bradtraversy/docker-node-mongo

version: '3'

services:
  app:
    container_name: zkusebna-kobylisy
    build: .
    ports:
      - '80:3000'
    volumes:
      - ../../:/usr/src/app/
      - ./run.sh:/run.sh
      - app-node-modules:/usr/src/app/node_modules/
      - /etc/letsencrypt/live/rezervace.zkusebna-kobylisy.cz/cert.pem:/usr/src/app/credentials/cert.pem
      - /etc/letsencrypt/live/rezervace.zkusebna-kobylisy.cz/privkey.pem:/usr/src/app/credentials/privkey.pem

  mongo:
    container_name: zkusebna-kobylisy-mongo
    image: mongo
    expose:
      - '27017'

volumes:
  app-node-modules: