version: '3'

services:
  nginx:
    container_name: zkusebna-kobylisy-nginx
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/rezervace.zkusebna-kobylisy.cz/cert.pem:/ssl/cert.pem
      - /etc/letsencrypt/live/rezervace.zkusebna-kobylisy.cz/privkey.pem:/ssl/privkey.pem
    depends_on:
      - app

  app:
    container_name: zkusebna-kobylisy
    image: relli/zkusebna-kobylisy:${LATEST_TAG}
    expose:
      - 3000
    volumes:
      - ../../.env.local:/usr/src/app/.env.local
      - ../../credentials:/usr/src/app/credentials
      - ./run.sh:/run.sh
      - app-node-modules:/usr/src/app/node_modules/

  mongo:
    container_name: zkusebna-kobylisy-mongo
    image: mongo
    expose:
      - 27017

volumes:
  app-node-modules:
