name: Tests

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.14.2

      - name: Install packages
        uses: toptal/davinci-github-actions/yarn-install@v5.0.0

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test
