name: Publish to production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: false

jobs:
  build:
    name: Publish to production
    runs-on: ubuntu-latest
    steps:
      - name: Verify tag
        if: ${{ github.event.inputs.tag != '' }} 
        run: |
          [[ $(git tag -l ${{ github.event.inputs.tag }}) ]] && echo "PARSED_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV || echo "Tag ${{ github.event.inputs.tag }} does not exist" && exit 1

      - name: Checkout tags
        if: ${{ github.event.inputs.tag == '' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag
        if: ${{ github.event.inputs.tag == '' }}
        run: |
          echo "PARSED_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Connect to DigitalOcean and execute deployment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_KEY }}
          passphrase: ${{ secrets.DO_KEY_PASSPHRASE }}
          script: |
            cd zkusebna-kobylisy-2.0
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            LATEST_TAG=${{ env.PARSED_TAG }} make production run

      - name: Print summary
        run: |
          echo "Version **${{ env.PARSED_TAG }}** was successfully deployed to production :rocket:" >> $GITHUB_STEP_SUMMARY
